---
title: "ggplot-in-class"
output: html_document
date: "2022-09-29"
---

```{r echo=FALSE}
# Custom options for knitting
knitr::opts_chunk$set(
  message = FALSE,
  warning = FALSE,
  error = FALSE, 
  collapse = TRUE,
  comment = "#",
  fig.height = 5,
  fig.width = 5,
  fig.align = "center",
  cache = FALSE
) 
```

```{r}
#install.packages('ggplot2')
library(ggplot2)
data(diamonds)
head(diamonds)
```
```{r}
ggplot(diamonds,aes(y=price,x=carat)) + 
                geom_point(col='blue',alpha=.1,shape=1,size=2) + 
                labs(y='price in $', x='carat score') + 
                geom_smooth(col='red')
```

```{r}
ggplot(diamonds,aes(y=price,x=carat)) + 
                geom_point(col='blue',alpha=.1,shape=1,size=2) + 
                labs(y='price in $', x='carat score') + 
                coord_trans(x='log10' , y='log10') +
                geom_smooth(col='red')
```
```{r}
ggplot(diamonds,aes(y=price,x=carat,col=color)) + 
                geom_point() + 
                labs(y='price in $', x='carat score')
```

```{r}
ggplot(diamonds,aes(y=price,x=carat,col=depth)) + 
                geom_point() + 
                labs(y='price in $', x='carat score')
```

```{r, fig.width=8,fig.height=2}
ggplot(diamonds,aes(y=price,x=carat,col=depth)) + 
                geom_point() + 
                facet_grid(~color) +
                labs(y='price in $', x='carat score')
```

```{r}
ggplot(diamonds,aes(depth)) + geom_histogram(col='grey',fill='lightblue',binwidth = .5)
```

```{r}
ggplot(diamonds,aes(depth)) + geom_histogram(col='grey',fill='lightblue',binwidth = .5) +
                            facet_wrap(~cut)
```
```{r}
ggplot(diamonds,aes(depth,fill=cut)) + geom_histogram(binwidth = .5,col='black',position='identity',alpha=.5)
```




```{r, fig.height = 3,fig.width = 1.5}
ggplot(diamonds,aes(y=price)) + geom_boxplot()
```

```{r}
length(unique(diamonds$cut))
ggplot(diamonds,aes(y=price,x=cut)) + geom_boxplot(col='darkgrey',fill='lightblue')
```

