---
title: "viz lecture"
output: html_document
date: "2022-09-20"
---

```{r}
library(MASS)
data(Cars93)

head(Cars93)

barplot(table(Cars93$AirBags),col = c("red","green","dodgerblue"),cex.lab=1.3)
box()
```


```{r}
table(Cars93$AirBags,Cars93$Origin)

barplot(table(Cars93$AirBags,Cars93$Origin),col = c(2,3,4),beside = T, ylim = c(0,40))
legend(x=5.5, y=38, title="Airbags", legend = c("Driver & Passenger",'Driver Only','None'),fill = c(2,3,4))
```

```{r}
pie(table(Cars93$AirBags),col=c(2,3,4),cex=1.3, main="Frequency Distribution of Airbag Usage")
#round(table(Cars93$AirBags)/nrow(Cars93),3)
legend(x=1, y=0, title="Airbags", legend = c('17.2%','46.2%','36.6%'),fill = c(2,3,4))
```
##
```{r}
plot(Cars93$MPG.city,Cars93$MPG.highway,ylim = c(10,50),pch=16,xlim=c(10,50))
stripchart(Cars93$MPG.city,method="stack",add=T,pch=16,at=10,cex.axis=1.2,cex.lab=1.2,col='blue')
stripchart(Cars93$MPG.highway,method='stack',add=T,pch=16,at=10,vertical=T,col='blue')
```

```{r}
layout(matrix(1:2, nrow = 1, byrow = T))
#layout.show(n=2)
plot(Cars93$EngineSize,Cars93$Price)
plot(Cars93$MPG.city, Cars93$Price)
```

```{r}
layout(matrix(c(1,0,2,3),byrow = T,nrow = 2), heights=c(.8,1.2), widths=c(1,.5))
#layout.show(n=3)
boxplot(Cars93$MPG.city,horizontal = T)
plot(Cars93$MPG.city,Cars93$MPG.highway)
boxplot(Cars93$MPG.highway)
```

```{r}
plot(1:10,1:10)
text(c(3,5.5,8),c(4,4,9),c('first','second','third'))
```





